import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Roboto, Space_Grotesk} from "next/font/google";
import { Roboto_Mono } from "next/font/google";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({weight: ["400"], subsets: ["latin"], variable: "--space-grotesk"});
const roboto = Roboto({weight: ["400"], subsets: ["latin"], variable: "--roboto-mono"});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <style  global>{`
        h1, h2, h3, h4 {
          font-family: ${spaceGrotesk.style.fontFamily};
        }
      `}</style>
      <body
        className={`${roboto.className} antialiased lg:mx-36 xs:mx-6 text-slate-500 bg-zinc-200 leading-relaxed selection:bg-slate-700 selection:text-slate-300
        `}
      >
        {children}
      </body>
    </html>
  );
}
